 'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {createCacheThrashChecker, wireCacheThrashDeps} = require('../src/cache-thrash');
const base={cacheThrashMinRequests:3,cacheThrashRingSize:50,cacheThrashSpikeRatio:3,cacheThrashInputSpikeRatio:2,cacheThrashIdleResetMs:100};
function harness(overrides={},factory=createCacheThrashChecker){let time=0;const checker=factory({...base,...overrides},{now:()=>time});return {checker,set:v=>time=v,add:(n=10,project='p',input=100)=>checker.check(project,'model',{input_tokens:input,cache_creation:{ephemeral_1h_input_tokens:n}}),seed(){for(let i=0;i<3;i++){time=i*10;this.add();}}};}
test('A idle threshold suppresses warm write, per-project age and exact boundary',()=>{const h=harness();h.seed();h.set(119);assert.equal(h.add(100).shouldAlert,true);const j=harness();j.seed();j.set(120);assert.equal(j.add(100).shouldAlert,false);assert.equal(j.add(100).details.avgCacheWrite1hPrior,10);const k=harness();k.seed();k.set(1000);k.add(10,'other');assert.equal(k.add(100).shouldAlert,false);});
test('B repeated spike after idle alerts',()=>{const h=harness();h.seed();h.set(120);h.add(1000);h.set(121);assert.equal(h.add(1000).shouldAlert,true);});
test('C steady-state spike alerts',()=>{const h=harness();h.seed();h.set(21);assert.equal(h.add(100).shouldAlert,true);});
test('D regression and nonfinite timestamps use normal alert rules',()=>{for(const t of [-1,NaN,Infinity,-Infinity]){const h=harness();h.seed();h.set(t);assert.equal(h.add(100).shouldAlert,true);}const h=harness();h.seed();h.set(NaN);h.add(10);h.set(1000);assert.equal(h.add(100).shouldAlert,true);});
test('E disabled output/status parity with retained original checker',()=>{const box={module:{exports:{}},console,require};vm.runInNewContext(fs.readFileSync('./test/fixtures/cache-thrash-baseline.js','utf8'),box);const a=harness({cacheThrashIdleResetMs:0}),b=harness({cacheThrashIdleResetMs:0},box.module.exports.createCacheThrashChecker);for(const [t,n] of [[0,10],[1,10],[2,10],[10000,100],[10001,50],[NaN,10],[-1,100]]){a.set(t);b.set(t);assert.equal(JSON.stringify(a.add(n)),JSON.stringify(b.add(n)));assert.equal(JSON.stringify(a.checker.getStatus('p')),JSON.stringify(b.checker.getStatus('p')));}});
test('F warm write excluded from baseline and ring eviction',()=>{const h=harness({cacheThrashRingSize:4});h.seed();h.set(120);h.add(1000);h.set(121);const r=h.add(31);assert.equal(r.details.avgCacheWrite1hPrior,10);assert.equal(r.shouldAlert,true);});
test('G original guards remain',()=>{const off=harness({cacheThrashMinRequests:0});assert.equal(off.add(100),undefined);const h=harness();assert.equal(h.add(100).shouldAlert,false);assert.equal(h.add(100).insufficientBaseline,true);const z=harness();z.add(0);z.add(0);z.add(0);const r=z.add(100);assert.equal(r.shouldAlert,false);assert.equal(r.insufficientBaseline,true);});
test('B1-A enabled getStatus is sufficient after warm start with usable positive prior entries',()=>{const h=harness({cacheThrashRingSize:4});h.seed();h.set(120);const r=h.add(1000);assert.equal(r.shouldAlert,false);assert.equal(h.checker.getStatus('p').warm,true);assert.equal(h.checker.getStatus('p').insufficientBaseline,false);});
test('B1-B enabled getStatus is insufficient once all eligible normal entries are evicted',()=>{const h=harness({cacheThrashRingSize:4});h.seed();h.set(21);h.add();assert.equal(h.checker.getStatus('p').insufficientBaseline,false);for(const t of [121,221,321,421]){h.set(t);h.add(1000);}assert.equal(h.checker.getStatus('p').warm,true);assert.equal(h.checker.getStatus('p').insufficientBaseline,true);});
test('clock injection reaches checker through composition seam',()=>{const deps={ledger:{}};let observed;const clock=()=>123;wireCacheThrashDeps(base,deps,{now:clock,createCacheThrashChecker:(cfg,seams)=>{observed=seams.now;return {check(){},getStatus(){}};}});assert.equal(observed,clock);});
